// <auto-generated />
namespace Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedDataBreaches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedDataBreaches));
        
        string IMigrationMetadata.Id
        {
            get { return "202106151917361_addedDataBreaches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
